[package]
name = "raytracer"
version = "0.1.0"
edition = "2024"

[dependencies]
indicatif = { version = "0.18.0", features = ["rayon", "improved_unicode"] }
anyhow = "1.0.98"
num = "0.4.3"
rand = "0.9.1"
rayon = "1.10.0"
thiserror = "2.0.12"
